services:
  db:
    image: postgres
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PWD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}

  web:
    build:
      context: .
      dockerfile: src/Dockerfile
    image: node
    volumes:
      - .:/usr/src/
    working_dir: /usr/src/
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always
